version: "3"
services:
  db:
    image: mariadb:latest
    volumes:
      - "./.data/db:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ".:/var/www/html/wp-content/themes/${WORDPRESS_THEME_NAME}"
      - "./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini"
      - "./wp-content/plugins:/var/www/html/wp-content/plugins"
      - "./wp-content/uploads:/var/www/html/wp-content/uploads"
    links:
      - db
      - smtp
    ports:
      - ${WORDPRESS_PORT}:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:${MYSQL_PORT}
      DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}

  smtp:
    image: mailhog/mailhog
    ports:
      - ${MAILHOG_SMTP_PORT}:${MAILHOG_SMTP_PORT} # smtp server
      - ${MAILHOG_UI_PORT}:${MAILHOG_UI_PORT} # web ui
